### ISSUE TITLE
Module for EasyWorship Presentation Software

### ISSUE THREAD

**Issue by andybantly** [bitfocus/companion-module-softouch-easyworship#1]
### New module request for EasyWorship presentation software

Hello, first of all thank you for the bitfocus companion system.

I'm a developer at Softouch, Inc. the maker of [EasyWorship](https://www.easyworship.com/) presentation software.
I've been doing research to see if EasyWorship can be controlled by a Stream Deck controller.  I've used Companion with two generic protocols, TCP and MQTT.  I used TCP to send commands to EasyWorship.  EasyWorship published these messages as topics to the MQTT broker.  The MQTT broker then relayed these commands back to Companion where I used instance feedback to control the button states.  Here is an image of companion controlling EasyWorship.
(https://user-images.githubusercontent.com/24298392/119686424-ee7cb500-be0b-11eb-9867-72fda29fe733.jpg).

Ideally, we would like to be officially supported by Companion.  Does companion work like MQTT where messages can be retained so that new connections will automatically know the state of the software it is controlling?  What do we need to provide to you to get started being supported?  How much does it cost? Our clients (churches) use our software to control their media, stage, and presentation.  They are screaming at us to be able to be controlled by a stream deck controller.

Thanks and regards
Andy Bantly
abantly@easyworship.com

**Comment by JITZEH** [comment]
https://github.com/bitfocus/companion-module-generic-mqtt

**Comment by jeff-vanhorn** [comment]
Would it be possible to remove the double 't' in the repo name? Company name is softouch. I am taking over this project for Andy, and did not realize the repo request was already started, so there may be a duplicate as I just went through the git add package process.

Thank you
Jeff V.

**Comment by josephdadams** [comment]
Done and I gave you write access

**Comment by JITZEH** [comment]
Hey @jeff-vanhorn,

Is the module usable soon? or do you just started?

**Comment by jeff-vanhorn** [comment]
> Hey @jeff-vanhorn,
> 
> Is the module usable soon? or do you just started?

It is fully functional, we are in the process of getting the module approved.

**Comment by josephdadams** [comment]
Module is in beta builds now
